demo:
  Config: /home/vmehta/hmnd/hmnd_playground/vmehta/vislam/vslam-lab/configs/config_demo.yaml
  Module: orbslam3
  NumRuns: 1
  Parameters:
    mode: mono-vi
    verbose: 1
    vocabulary: /home/vmehta/hmnd/hmnd_playground/vmehta/vislam/vslam-lab/Baselines/ORB_SLAM3/Vocabulary/ORBvoc.txt
