demo:
  Config: /home/vmehta/hack-space/VSLAM-LAB/configs/config_demo.yaml
  Module: orbslam3-dev
  NumRuns: 1
  Parameters:
    mode: mono-vi
    verbose: 1
    vocabulary: /home/vmehta/hack-space/VSLAM-LAB/Baselines/ORB_SLAM3-DEV/Vocabulary/ORBvoc.txt
